version: "3"
services:
  redis:
       image: 'redis:latest'
  server:
      container_name: bitwala_server
      build:
          context: ./bitwala_server
          dockerfile: Dockerfile
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
      ports:
          - "4000:4000"
      volumes:
          - ./server:/usr/src/app
   

